# Generated by Django 4.2.2 on 2023-07-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('is_active', models.BooleanField(default=False)),
                ('borrowed_book_status', models.BooleanField(default=False)),
                ('borrowed_book_id', models.CharField(max_length=20)),
            ],
        ),
    ]
