# Generated by Django 4.2.2 on 2023-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='librarian_name',
            field=models.CharField(default='Not Set Yet', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
