# Generated by Django 4.2.2 on 2023-07-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_librarian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='librarian_name',
            field=models.CharField(max_length=20),
        ),
    ]
